//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class PlayerShootingState : IPlayerState
{
	float shootForce;
	float shootForceChargeRate = 50f;
	float maxCharge = 5f;
		
	public PlayerShootingState (Player player) : base(player)
	{
		
	}
	
	public override void HandleInput(){
		if (disabled) return;
		
		if (Input.GetKeyDown (KeyCode.Space)) {
			shootForce = 0f;
		}
		
		if (Input.GetKey (KeyCode.Space) ){
			shootForce += shootForceChargeRate *Time.deltaTime;
			
			
		}
		
		if (Input.GetKeyUp (KeyCode.Space)){
			
			// release
			Debug.Log (shootForce);
		}
		
		//Debug.Log (shootForce);
	} 
	
	public override void Start(){
	
	}
	
	public override void FixedUpdate(){
		
	}
	public override void Update(){
		HandleInput ();
	}
	
	public override void Disable(){
		disabled = true;
	}
	
	public override void Enable(){
		disabled = false;
	}
}

