//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public static class PlayerPrefVariables
{
		public static string GOOD_COUNT = "good count";
		public static string BAD_COUNT = "bad count";
		public static string LAST_LEVEL = "LastLevel";
		
		public static string KILL_COUNT = "KillCount";
		public static string TOTAL_MEMBERS = "TotalEnemies";
		public static string POWER_USAGE = "PowerUsage";
}


