//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class PlayerJumpingState : IPlayerState
{	
	public PlayerJumpingState (PlayerController player) : base(player)
	{
	}
	
	public override void HandleInput(){
		if (disabled) return;
		if (Input.GetKeyUp(KeyCode.UpArrow) && player.grounded)
			player.rigidbody2D.AddForce(Vector2.up*player.jumpForce);
	} 
	
	public override void Start(){
		
	}
		
	public override void FixedUpdate(){
	}
	
	public override void Update(){
		HandleInput ();
	}
	
	public override void Disable(){
		disabled = true;
	}
	
	public override void Enable(){
		disabled = false;
	}
}
